# SwiftLint Configuration for SwiftAssessment
# MVI Foundation Sprint - CI-2

# Included paths
included:
  - name

# Excluded paths
excluded:
  - Pods
  - .build
  - DerivedData
  - nameTests
  - nameUITests

# Disabled rules (none for now, using defaults)
disabled_rules:
  - todo
  - trailing_comma

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

indentation: 4

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

# Naming conventions
type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - db
    - km

# Force unwrapping
force_cast: warning
force_try: warning
force_unwrapping: warning

# Other rules
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

discouraged_optional_boolean: warning

vertical_whitespace:
  max_empty_lines: 2

# Custom rules
custom_rules:
  no_print_statements:
    name: "Print Statements"
    regex: "print\\("
    match_kinds:
      - identifier
    message: "Use proper logging instead of print()"
    severity: warning
